name: dataexplore 
version: 'latest'
version-script: git describe --abbrev=1 --tags
summary: data plotting and analysis package
description: |
  DataExplore is an open source desktop application for data analysis and plotting
  intended for use in both research and education. It is intended primarily for
   non-programmers who need to do relatively advanced table manipulation methods.

grade: stable 
confinement: strict
icon: ../img/logo.png
  
apps:
  dataexplore:
    command: desktop-launch $SNAP/bin/dataexplore
    plugs: [home,x11,unity7]
    
parts:
  dataexplore:    
    plugin: python
    python-version: python3
    source: ../
    stage-packages: 
      [python3-tk,fontconfig-config,fonts-freefont-ttf,ttf-ubuntu-font-family,
       ttf-mscorefonts-installer]
    after: [desktop-glib-only]
      
  files: #to deal with problem finding init.tcl
    plugin: dump
    source: /usr/share/tcltk/
    organize:
        '*': ./usr/lib/
